Trip's branch
Threelivestoken/RFP1 pull request #4
Opened 2024-02-22 18:27 UTC by Threelivestoken

I merged the datasets I think without error

2024-02-22 18:35 UTC, bsilver3 requested changes
It doesn't look like you have df defined. I get an error on line 8 in your second cell when I run the code myself. Did you have a temporary lingering variable in Jupyter Notebook that you didn't define in this version?

2024-02-22 18:41 UTC, bsilver3 reviewed
It looks like you fixed the issue I mentioned before. I would advise to take a deeper look at the cons of dropping all duplicate rows/IDs. What happens if a customer has multiple transactions, so their ID shows up multiple times? Are we losing information?

2024-02-28 18:08 UTC, Threelivestoken commented
I cant figure out what I did wrong in the code, can you help?

2024-03-01 17:46 UTC, LastCa11 approved these changes

2024-03-01 17:46 UTC, merged